language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - mkdocs build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: site
    on:
      branch: master
