language: bash  # python

node_js:
  - "14.15.1"

python:
  - "3.7"

jobs:
  include:
    - language: node_js
      node_js: 14.15.1
      script:
        - npm install
        - npm run test || travis_terminate 1

    - language: python
      python: 3.7
      script:
        - pip install -r requirements.txt
        - mkdocs build
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          local_dir: site
          on:
            branch: master
