site_name: Extension CLI • User Guide
site_description: Command-line build tools for chromium extension development.
site_author: '@mobilefirstllc'
docs_dir: ./guide
site_url: https://oss.mobilefirst.me/extension-cli/
repo_url: https://github.com/MobileFirstLLC/extension-cli
repo_name: Github
edit_uri: blob/master/guide/
use_directory_urls: true

nav:
  - "Getting Started":
    - Intro: index.md
    - Installation: 01-getting-started.md
    - Configuration: 02-configuration.md
  - "Commands":
    - 'extension-cli': 08-xt-create.md
    - 'xt-build': 03-xt-build.md
    - 'xt-clean': 04-xt-clean.md
    - 'xt-docs': 05-xt-docs.md
    - 'xt-sync': 06-xt-sync.md
    - 'xt-test': 07-xt-test.md
  - "Resources":
    - Release Notes: 09-release-notes.md
    - Helpful References: 12-helpful.md
    - Showcase: 10-showcase.md
    - Tech Stack: 11-stack.md
    - Development: 13-cli-development.md
  - "Source Code":
    - Github: https://github.com/MobileFirstLLC/extension-cli

extra_css:
 - assets/custom.css
extra_javascript:
  - "https://buttons.github.io/buttons.js"

theme:
  name: material
  logo: '/extension-cli/assets/images/guide_icon.svg'
  favicon: '/extension-cli/assets/images/favicon.png'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
  palette:
    scheme: slate
    primary: amber
    accent: amber
  font:
    text: Inter

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline

google_analytics:
  - !!python/object/apply:os.getenv ['UA-129118591-7']
  - auto
