image: node:latest

stages:
  - install
  - pages
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script: yarn
  artifacts:
    paths:
      - node_modules/

pages:
  stage: pages
  script:
    - npm run test
    - npm run docs
  artifacts:
    paths:
      - public/
  only:
    - master

store_publish:
  stage: publish
  script:
    - npm run build
    # - npx cws-upload $cid $sec $tkn $zip $eid;
  artifacts:
    paths:
      - $zip
  only:
    - tags
