language: node_js

node_js:
  - "12.16.3"

cache:
  directories:
  - node_modules

before_script:
  - npm run test -- --coverage

script:
  - npm run docs
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: /public/documentation
    on:
      branch: master

  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file: $zip
    on:
      tags: true
