name: NPM Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Tag name
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: npm install
      - run: npm run test

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          dry-run: true
          tag: ${{ env.TAG }}
          token: ${{ secrets.NPM_TOKEN }}

      - name: Github Release
        uses: ncipollo/release-action@v1
        if: {{ contains(env.TAG, 'alpha') == false && contains(env.TAG, 'beta') == false }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
